### ISSUE TITLE
Function Not Implemented on build

### ISSUE THREAD

**Issue by ahdyt** [termux/libandroid-shmem#11]
make: gcc: Function not implemented
make: *** [Makefile:22: test-after-fork] Error 127

**Comment by ahdyt** [comment]
I'm on nix-on-droid trying to adopt this lib shmem to make it work with postgresql, but I can't compile it.

**Comment by Grimler91** [comment]
Do you have a compiler and other build-essential programs installed?

**Comment by ghost** [comment]
I guess that's proot issue since Nix-On-Droid app relies on it. Note that proot isn't stable and may not work on some devices. You can go through https://github.com/termux/proot/issues.

Regarding shmem: latest versions of proot support SysV IPC which includes shared memory and semaphores, so you may want to request authors of Nix-On-Droid to update the bundled proot binary and use option "--sysvipc".
