### ISSUE TITLE
correct implementation

### ISSUE THREAD

**Issue by mgood7123** [termux/libandroid-shmem#8]
what differences are there from the glibc api and this

**Comment by ghost** [comment]
GNU libc implements it through the related Linux system calls: shmat(), shmctl(), shmdt(), shmget(). But we can't use them due to seccomp restrictions. So we have to implement such functions in userspace. Here this is done through the Ashmem Android subsystem.

Really you shouldn't see any difference in runtime.

**Comment by mgood7123** [comment]
ok, as i am implementing a Realtime SysV api:

https://github.com/mgood7123/AndroidCompositor/tree/master/app/src/main/jni/SysV_api

https://github.com/mgood7123/AndroidCompositor/blob/master/app/src/main/jni/compositor_examples/LowMemoryKillerTest.cpp

and am wondering how i could get around the fact that shared memory cannot be safely deallocated since processes can be killed at any time
